"""Regenerate data-test/iri-label-fixture.ttl by REAL writer emission.

Phase 8 / Plan 08-03 (D-09). The flag-on label fixture feeds the property audit
so the regenerated chemical + gene-association SHACL shapes gain an rdfs:label
constraint sourced from genuine emission (never hand-authored) -- mirroring the
Phase-7 provenance-fixture method (07-04). The fixture is produced by running
both writers with enable_iri_labels=True (and enable_bern2=True for the minted
':' predicate labels) over tiny entity/gene dicts whose chemical/gene/component
subjects carry populated label maps, then concatenating the two outputs into one
Turtle file the audit can read.

Run: python scripts/generate_iri_label_fixture.py
Deterministic and network-free; re-running yields byte-identical output.
"""

import os
import tempfile
import types

from aopwiki_rdf.rdf.writer import write_aop_rdf, write_genes_rdf

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE_PATH = os.path.join(BASE_DIR, "data-test", "iri-label-fixture.ttl")
# The repo prefixes.csv declares every prefix the predicate-label block needs.
PREFIX_CSV = os.path.join(BASE_DIR, "prefixes.csv")


def _labels_on_config():
    """Flag-on config: labels for the main file, labels + bern2 for genes."""
    return types.SimpleNamespace(
        enable_iri_labels=True,
        emit_legacy_predicates=False,
        enable_bern2=True,
    )


def _main_entities():
    """Tiny main-file entities: a labeled ChEBI xref (cheminf:000407), a labeled
    Entrez/UniProt gene xref, and a labeled GO component -- the chemical-xref /
    gene-xref / component subjects the chemical + gene-association shapes target,
    all carrying rdfs:label via real emission.

    Deliberately NO chemical ENTITY (cheminf:000000): the production-derived
    ChemicalShape requires several fully-populated chemical-entity properties
    (dc:source, dcterms:isPartOf, cheminf:000568) that a tiny synthetic entity
    cannot satisfy, and the ChemicalShape is validated against production data/
    -- not this label fixture. The fixture only needs the labeled ChEBI xref
    (cheminf:000407) to exercise the ChemicalXrefShape rdfs:label constraint."""
    return {
        "aopdict": {}, "kedict": {}, "kerdict": {}, "strdict": {},
        "taxdict": {}, "bioactdict": {}, "bioobjdict": {}, "prodict": {},
        "chedict": {},
        "bioprodict": {
            "p1": {
                "dc:identifier": "go:0008150",
                "dc:title": '"biological_process"',
                "dc:source": '"GO"',
            }
        },
        "hgnclist": [],
        "ncbigenelist": ["ncbigene:7157"],
        "uniprotlist": ["uniprot:P04637"],
        "listofcas": [], "listofinchikey": [], "listofcomptox": [],
        "listofchebi": ["chebi:16842"],
        "listofchemspider": [], "listofwikidata": [],
        "listofchembl": [], "listofpubchem": [], "listofdrugbank": [],
        "listofkegg": [], "listoflipidmaps": [], "listofhmdb": [],
        "symbol_lookup": {},
        "chem_label_by_iri": {
            "chebi:16842": "Formaldehyde",
        },
        "gene_label_by_iri": {
            "ncbigene:7157": "TP53",
            "uniprot:P04637": "TP53",
        },
    }


def _gene_data():
    """Tiny genes-file data with a KE/KER provenance union (so the minted
    ':' predicates + their rdfs:label rows emit) and labeled gene xrefs."""
    return {
        "kedict": {
            "ke1": {
                "dc:identifier": "aop.events:100",
                "edam:data_1025": ["hgnc:11998", "hgnc:108"],
                "_genes_regex": ["hgnc:11998", "hgnc:108"],
                "_genes_ner": ["hgnc:108"],
            }
        },
        "kerdict": {},
        "hgnclist": ["hgnc:11998"],
        "geneiddict": {"hgnc:11998": []},
        "listofentrez": ["ncbigene:7157"],
        "listofensembl": ["ensembl:ENSG00000141510"],
        "listofuniprot": ["uniprot:P04637"],
        "symbol_lookup": {"11998": "TP53"},
        "gene_label_by_iri": {
            "ncbigene:7157": "TP53",
            "ensembl:ENSG00000141510": "TP53",
            "uniprot:P04637": "TP53",
        },
    }


def main():
    config = _labels_on_config()
    with tempfile.TemporaryDirectory() as tmp:
        main_out = os.path.join(tmp, "main.ttl")
        genes_out = os.path.join(tmp, "genes.ttl")
        write_aop_rdf(main_out, _main_entities(), PREFIX_CSV, config=config)
        write_genes_rdf(genes_out, _gene_data(), config=config)
        main_ttl = open(main_out, encoding="utf-8").read()
        genes_ttl = open(genes_out, encoding="utf-8").read()

    header = (
        "# data-test/iri-label-fixture.ttl\n"
        "# GENERATED by scripts/generate_iri_label_fixture.py -- do NOT hand-edit.\n"
        "# Flag-on (enable_iri_labels=True, enable_bern2=True) real-emission\n"
        "# fixture: labeled chemical/gene/component subjects + external + minted\n"
        "# predicate labels. Audit input for the rdfs:label SHACL constraint.\n\n"
    )
    # Concatenate the two emitted files. The genes block redeclares the prefixes
    # it needs (GENES_PREFIXES + the prov: carve-out), so the combined Turtle is
    # self-consistent and parses as one graph.
    with open(FIXTURE_PATH, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(main_ttl)
        f.write("\n\n")
        f.write(genes_ttl)

    # Parse-check so a malformed fixture fails loudly here, not in the audit.
    from rdflib import Graph
    Graph().parse(FIXTURE_PATH, format="turtle")
    print(f"Wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
