name: Update Zenodo Record with New Version

on:
  workflow_dispatch:

jobs:
  update-zenodo-record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install curl and jq
        run: sudo apt-get install -y curl jq

      - name: Create a New Version of the Deposition
        id: new_version
        run: |
          response=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
                        "https://zenodo.org/api/deposit/depositions/${{ secrets.ZENODO_DEPOSITION_ID }}/actions/newversion")
          new_draft_url=$(echo "$response" | jq -r '.links.latest_draft')
          new_draft_response=$(curl -s -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" "$new_draft_url")
          new_deposition_id=$(echo "$new_draft_response" | jq -r '.id')
          new_bucket_url=$(echo "$new_draft_response" | jq -r '.links.bucket')
          echo "new_deposition_id=$new_deposition_id" >> $GITHUB_ENV
          echo "new_bucket_url=$new_bucket_url" >> $GITHUB_ENV

      - name: Debug New Bucket URL
        run: echo "$new_bucket_url"

      - name: Upload files to Zenodo
        run: |
          for file in data/*.ttl; do
            curl --progress-bar -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
                  --upload-file $file "$new_bucket_url/$(basename $file)"
          done

      - name: Publish Updated Zenodo Record
        run: |
          curl -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST "https://zenodo.org/api/deposit/depositions/$new_deposition_id/actions/publish"
