name: Update Zenodo Record

on:
  workflow_dispatch:

jobs:
  update-zenodo-record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install curl and jq
        run: sudo apt-get install -y curl jq

      - name: Get Latest Deposition (Draft) from Zenodo
        id: get_deposition
        run: |
          # Retrieve the draft of the latest version of the deposition
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
                           "https://zenodo.org/api/deposit/depositions/${{ secrets.ZENODO_DEPOSITION_ID }}")
          echo "$response" | jq '.'
          deposition_id=$(echo $response | jq -r '.id')
          bucket_url=$(echo $response | jq -r '.links.bucket')
          echo "{deposition_id}={$deposition_id}" >> $GITHUB_ENV
          echo "{bucket_url}={$bucket_url}" >> $GITHUB_ENV

      - name: Debug Bucket URL
        run: echo "$bucket_url"

      - name: Upload files to Zenodo with retry
        run: |
          for file in data/*.ttl; do
            n=0
            until [ $n -ge 5 ]
            do
              curl --progress-bar -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
                   --upload-file $file "$bucket_url/$(basename $file)" && break
              n=$((n+1))
              echo "Upload failed. Retrying in 10 seconds..."
              sleep 10
            done
          done


      - name: Publish Updated Zenodo Record
        run: |
          curl -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST "https://zenodo.org/api/deposit/depositions/${{ env.deposition_id }}/actions/publish"
